version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: flower-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: floweradmin
      MONGO_INITDB_ROOT_PASSWORD: flowerpassword
      MONGO_INITDB_DATABASE: flowerdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile
      target: seeder
    container_name: flower-mongo-seed
    command: ["node", "seed-data.js"]
    environment:
      - MONGODB_URI=mongodb://floweradmin:flowerpassword@mongodb:27017/flowerdb?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://floweradmin:flowerpassword@mongodb:27017/flowerdb?authSource=admin
      - JWT_SECRET=b7e715694c65e315219213192452b43a9030a528625e19a4843b381517865268
      - NEXT_PUBLIC_APP_URL=http://localhost:3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-seed:
        condition: service_completed_successfully
    networks:
      - app-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: flower-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: floweradmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: flowerpassword
      ME_CONFIG_MONGODB_URL: mongodb://floweradmin:flowerpassword@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
