services:
  mongodb:
    image: mongo:latest
    container_name: flower-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: floweradmin
      MONGO_INITDB_ROOT_PASSWORD: flowerpassword
      MONGO_INITDB_DATABASE: flowerdb
    volumes:
      - mongodb-data:/data/db
    networks:
      - flower-network

  mongo-admin:
    image: mongo-express:latest
    container_name: flower-mongo-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: floweradmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: flowerpassword
      ME_CONFIG_MONGODB_URL: mongodb://floweradmin:flowerpassword@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb
    networks:
      - flower-network

volumes:
  mongodb-data:
    name: flower-mongodb-data

networks:
  flower-network:
    name: flower-network 